Add button-image in search
ala-n/internship2021_ui pull request #46
Opened 2021-02-17 12:20 UTC by taraslaz10

2021-02-17 23:13 UTC, Zairbekov approved these changes

2021-02-18 11:55 UTC, abarmina commented on src/app/shared/custom-components/toolbar/search/search.component.html
> +  <button class="search-form__search-button-image"></button>
I think you can use only ```search-form__button```, since you need to specify one element (now there are two of them - picture and button)

2021-02-22 06:42 UTC, AlexanderBazukevich requested changes

2021-02-22 06:42 UTC, AlexanderBazukevich commented on src/app/shared/custom-components/toolbar/search/search.component.scss
>    min-width: 150px;
I suggest smth/ like this:
.search-form {
  max-width: 260px; //we can remove this after changing tags component
  margin-left: 1em;

  &__field {
    display: flex;
    border: $border-primary;
    border-radius: 25px;
  }

  &__input {
    width: 100%;
    font-size: 20px;
    border: none;
    border-radius: 25px;
    outline: none;
  }

  &__button {
    color: $blue-primary; //extract this to button shared styles
  }

2021-02-22 06:42 UTC, AlexanderBazukevich commented on src/app/shared/custom-components/toolbar/search/search.component.html
> +<form class="search-form">
Seems better create container for input and button and we can skip absolute positioning
>div class="search-form__field>
    >button class="search-form__button" mat-icon-button>  //we can use here "button button_c_blue" after extracting from css
      >mat-icon class="icon icon_s">search>/mat-icon>
    >/button>
   > input
      type="text"
      class="search-form__input"
      placeholder="Search"
      [formControl]="control"
      [matAutocomplete]="auto"
    />
  >/div>

2021-02-23 12:46 UTC, AlexanderBazukevich approved these changes

2021-02-23 12:51 UTC, abarmina approved these changes

2021-02-23 12:52 UTC, merged