Upgrade search
ala-n/internship2021_ui pull request #75
Opened 2021-03-03 10:04 UTC by taraslaz10

2021-03-03 20:47 UTC, AlexanderBazukevich requested changes

2021-03-03 20:47 UTC, AlexanderBazukevich commented on src/app/shared/models/tag.ts
> +  createdAt: Date;
createdAt and updatedAt are strings, Date isn`t js type

2021-03-03 20:47 UTC, AlexanderBazukevich commented on src/app/shared/services/tag.service.ts
>  export class TagsService {
In my opinion we must have one tags service with 2 requests for all tags and top tags.

2021-03-04 10:06 UTC, Zairbekov approved these changes

2021-03-04 10:48 UTC, taraslaz10 commented on src/app/shared/models/tag.ts
> +  createdAt: Date;
Ок!

2021-03-04 21:30 UTC, AlexanderBazukevich approved these changes

2021-03-04 22:34 UTC, merged